name: Test injector

on:
  workflow_dispatch:

env:
  AGENT_TESTS: nodejs java

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Test no agent
      run: |
          node jack-test/app.js &
          sleep 2
          java jack-test/JavaHello.java

    - name: Install Zig
      run: |
          ZIG_VERSION=$(cat zig-version | grep -v '^#' | sed 's/ZIG_VERSION=//; s/-r0//')
          echo "Install zig version $ZIG_VERSION"
          curl -L https://ziglang.org/download/$ZIG_VERSION/zig-x86_64-linux-$ZIG_VERSION.tar.xz | tar -xJf -
          echo $PWD/zig-x86_64-linux-$ZIG_VERSION  >> $GITHUB_PATH

    - name: Run make zig
      run: make zig-build

